port: 50095
serviceName: "notifications"
registryAddress: "consul-service:8500"
db:
  host: "reviews-db-service"
  port: 5432
  user: "postgres"
  password: "794613825Zx!"
  database: "notifications_db"
redisAddr: "redis-notifications-service.default.svc.cluster.local:6379"
redisPass: ""
kafka:
  addrs: [ "localhost:9092" ]
  notificationTopic: "notifications"