apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul-pod
          image: hashicorp/consul:latest
          ports:
            - containerPort: 8500
            - containerPort: 8600
