apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-mongodb
  template:
    metadata:
      labels:
        app: reviews-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          emptyDir: {}