#file: noinspection YAMLSchemaValidation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-microservice-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-microservice
  template:
    metadata:
      labels:
        app: reviews-microservice
    spec:
      containers:
        - name: reviews-microservice-pod
          imagePullPolicy: Always
          image: jmurv/reviews_svc:latest
          ports:
            - containerPort: 50085