#file: noinspection YAMLSchemaValidation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-microsvc-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-microsvc
  template:
    metadata:
      labels:
        app: reviews-microsvc
    spec:
      containers:
        - name: reviews-microsvc-pod
          imagePullPolicy: Always
          image: jmurv/reviews_svc:1.6
          ports:
            - containerPort: 50085
          envFrom:
            - secretRef:
                name: reviews-db-credentials