port: 50085
serviceName: "reviews"
db:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "794613825Zx!"
    database: "reviews_db"
registryAddr: "localhost:8500"
redisAddr: "localhost:6379"
redisPass: ""
kafka:
  addrs: ["localhost:9092"]
  notificationTopic: "notifications"