port: 50085
serviceName: "reviews"
db:
  host: "reviews-db-service"
  port: 5432
  user: "postgres"
  password: "794613825Zx!"
  database: "reviews_db"
registryAddress: "consul-service:8500" #<имя сервиса>.<namespace>.svc.cluster.local<:port>
redisAddr: "redis-reviews-service.default.svc.cluster.local:6379"#redis-reviews-service.default.svc.cluster.local:6379
redisPass: ""
kafka:
  addrs: ["localhost:9092"]
  notificationTopic: "notifications"