server:
  mode: "prod"

port: 50085
serviceName: "reviews"
registryAddress: "consul-service:8500" #<имя сервиса>.<namespace>.svc.cluster.local<:port>
db:
  host: "reviews-db-service"
  port: 5432
  user: "postgres"
  password: "794613825Zx!"
  database: "reviews_db"

redis:
  addr: "redis-reviews-service.default.svc.cluster.local:6379"
  pass: ""

kafka:
  addrs: [ "kafka-service.default.svc.cluster.local:9092" ]
  notificationTopic: "notifications"

jaeger:
  sampler:
    type: "const"
    param: 1
  reporter:
    LogSpans: true
    LocalAgentHostPort: "jaeger-service.default.svc.cluster.local:6831"