server:
  mode: "dev"

port: 50080
serviceName: "items"
registryAddr: "localhost:8500"

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "794613825Zx!"
  database: "items_db"

redis:
  addr: "localhost:6379"
  pass: ""

kafka:
  addrs: [ "localhost:9092" ]
  notificationTopic: "notifications"

  jaeger:
    sampler:
      type: "const"
      param: 1
    reporter:
      LogSpans: true
      LocalAgentHostPort: "localhost:6831"