server:
  mode: "prod"

port: 50080
serviceName: "items"
registryAddress: "consul-service:8500"

db:
  host: "items-db-service"
  port: 5432
  user: "postgres"
  password: "794613825Zx!"
  database: "items_db"

redis:
  addr: "redis-items-service.default.svc.cluster.local:6379"
  pass: ""

kafka:
  addrs: [ "kafka-service.default.svc.cluster.local:9092" ]
  notificationTopic: "notifications"

jaeger:
  sampler:
    type: "const"
    param: 1
  reporter:
    LogSpans: true
    LocalAgentHostPort: "jaeger-service.default.svc.cluster.local:6831"