port: 50080
serviceName: "items"
registryAddress: "consul-service:8500"
db:
  host: "items-db-service"
  port: 5432
  user: "postgres"
  password: "794613825Zx!"
  database: "items_db"
redisAddr: "redis-items-service.default.svc.cluster.local:6379"
redisPass: ""
kafka:
  addrs: [ "localhost:9092" ]
  notificationTopic: "notifications"