port: 50090
serviceName: "favorites"
registryAddress: "consul-service:8500"
db:
  host: "favorites-db-service.default.svc.cluster.local"
  port: 5432
  user: "postgres"
  password: "794613825Zx!"
  database: "favorites_db"
redisAddr: "redis-favorites-service.default.svc.cluster.local:6379"
redisPass: ""
kafka:
  addrs: [ "localhost:9092" ]
  notificationTopic: "notifications"