apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-db
  template:
    metadata:
      labels:
        app: reviews-db
    spec:
      containers:
        - name: reviews-db-pod
          image: postgres:15.0-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: reviews-db-credentials