port: 50100
serviceName: "query"
registryAddr: "localhost:8500"
redisAddr: "localhost:32712"
redisPass: ""
mongoAddr: "mongodb://localhost:32133"
kafka:
  addr: ["localhost:9092"]
  topics: ["users", "reviews", "items", "notifications", "favorites"]
  topicName:
    create: "create"
    update: "update"
    delete: "delete"
