#file: noinspection YAMLSchemaValidation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-microsvc-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-microsvc
  template:
    metadata:
      labels:
        app: notifications-microsvc
    spec:
      containers:
        - name: notifications-microsvc-pod
          imagePullPolicy: Always
          image: jmurv/notifications_svc:1.0
          ports:
            - containerPort: 50095
          envFrom:
            - secretRef:
                name: notifications-db-credentials