#file: noinspection YAMLSchemaValidation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-microsvc-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-microsvc
  template:
    metadata:
      labels:
        app: gateway-microsvc
    spec:
      containers:
        - name: gateway-microsvc-pod
          imagePullPolicy: Always
          image: jmurv/gateway_svc:latest
          ports:
            - containerPort: 8000