port: 50075
serviceName: "users"
registryAddress: "consul-service:8500"
db:
  host: "users-db-service"
  port: 5432
  user: "postgres"
  password: "794613825Zx!"
  database: "users_db"
redisAddr: "redis-users-service.default.svc.cluster.local:6379"
redisPass: ""
kafka:
  addrs: [ "localhost:9092" ]
  notificationTopic: "notifications"