#file: noinspection YAMLSchemaValidation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-microsvc-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items-microsvc
  template:
    metadata:
      labels:
        app: items-microsvc
    spec:
      containers:
        - name: items-microsvc-pod
          imagePullPolicy: Always
          image: jmurv/items_svc:1.0
          ports:
            - containerPort: 50080
          envFrom:
            - secretRef:
                name: items-db-credentials